### PR TITLE
Add expect script for running commands over serial.

### PR DESCRIPTION
**Pull request by volfyd**
Hi...it would be nice to have a small expect script to interact with the CLI on the serial port.

### CODE REVIEW

**Comment by htruong** [comment]
Thanks for the contribution!

Can we have the script take the device as a parameter?

**Comment by htruong** [comment]
Thanks for the improvements! Could I request another small change, since this is a small change, can you squash all the commits together and make it one commit?

**Comment by volfyd** [comment]
No problem. Done.

**Comment by htruong** [comment]
Thanks! I have tested the script, it worked as expected :+1:).

**Pull request merged**
