### PR TITLE
Small fixes and improvements

### PR DESCRIPTION
**Pull request by htruong**
Some small fixes:

- Do not generate the ext2fs image while building, pretty useless
- Move the rootfs to rootfs on repo root, so it's more discoverable

### CODE REVIEW

**Comment by tuyenld** [comment]
I sometime use `ext4` to generate debugging image, I can change everything in rootfs
I think we need to keep it for debugging too.

**Comment by dgsiegel** [comment]
> I sometime use `ext4` to generate debugging image, I can change everything in rootfs
> I think we need to keep it for debugging too.

If you just want to add new files, you can use the overlay. If you actually want to change files, a debug flag might make sense, as we probably will need that for the serial interface too at some point

@htruong would you mind using `.gitkeep` instead of `placeholder`? It seems that this file gets copied over, while all dot files shouldn't, if I understood the docs correctly.

**Comment by htruong** [comment]
Fixed. 

Yeah, I think we can have a debug build that will have ext4 image, that's going to be very nice. However, I think for now we should remove this because it does nothing.

**Review by dgsiegel — APPROVED** [review]
Looks good to me

**Comment by htruong** [comment]
Tested on my pi0w, works well enough for me!

**Pull request merged**
