### PR TITLE
Updated README and example camera.txt

### PR DESCRIPTION
**Pull request by PSF1**
Some changes in README.md and default camera.txt with options comments.

I added a Ubuntu example about how to connect to the camera prompt, and a camera.txt example file.

### CODE REVIEW

**Comment by htruong** [comment]
Thank you PSF1.

One small nit: can you "squash" the changes so it shows up as a single commit? 

In order to do so, you need to "rebase" your change based on the latest HEAD.

I usually do something like this:

```bash

$ git log --oneline
... It will show you 6 commits you've made: A, B, C, D, E (the "merge" one), F
Then a commit that is in the showmewebcam repo: G

$ git rebase -i G 
```

Now fix the line in front of the "merge" commit (E), so instead of saying "merge" it says "drop". Save it. Now your PR should not have the "merge" commit.

Then do it one more time, but instead of the line that says `pick A clean readme`, it says `reword A clean readme`, and every line following that line has a `pick B ...` fix it so it says `fix B ....` `fix C ...` Save it.

Then it will show you another file and you can change the commit message for the `clean readme` commit, fix it so it says: `Update README and example camera.txt` ([we should follow rule 5: Use imperative verbs here](https://chris.beams.io/posts/git-commit/#imperative)). Save the file and quit. You're done!

**Comment by PSF1** [comment]
Thanks so much for the explication, I will try to do it. : )

**Comment by PSF1** [comment]
Now? :_ D

**Comment by htruong** [comment]
Haha, it still has 8 separate commits, but I can help you...

**Comment by PSF1** [comment]
:_ D I'm sorry.

2 commits are mine and 6 are your and of Le Dinh-Tuyen, I think that I can't modify that.

I added you to my repository, to simplify you do changes.

**Comment by htruong** [comment]
I have fixed it and force-pushed it to your repository too. It requires some fiddling around with `git rebase`, but was not bad at all.

You see now, it has only one commit without the merges:
Screenshot_20201025_140458


Thank you for your help with the project.

**Comment by PSF1** [comment]
I see :_ D Thanx, The next time I'll study a bit more.

**Pull request merged**
