### PR TITLE
Support Raspberry Pi Zero v1.3 (no Wi-Fi)

### PR DESCRIPTION
**Pull request by tuyenld**
- We need overlays partion because of setting "dtoverlay=dwc2" in the config.txt
dwc2.dtbo will be looked for in the /boot/overlays
(see more: part "3.1: DTBs, overlays and config.txt" https://www.raspberrypi.org/documentation/configuration/device-tree.md)

- According to https://github.com/raspberrypi/firmware/blob/d46e089301ba5b2e6768c78d706e9d28370e3c1c/boot/overlays/README#L722 it read
Name:   dwc-otg
Info:   Selects the dwc_otg USB controller driver which has fiq support. This
        is the default on all except the Pi Zero which defaults to dwc2.
Load:   dtoverlay=dwc-otg
Params: <None>

This is not true. If the dwc2 wasn't use, you'll have an error:
$ journalctl --no-pager -u piwebcam
Feb 07 15:51:04 showmepicam piwebcam[153]: UVC: device open failed: No such file or directory (2).
Feb 07 15:51:04 showmepicam systemd[1]: piwebcam.service: Main process exited, code=exited, status=1/FAILURE
Feb 07 15:51:04 showmepicam systemd[1]: piwebcam.service: Failed with result 'exit-code'.

### CODE REVIEW

**Comment by tuyenld** [comment]
## dmesg log when dwc-otg was used
```bash
# dmesg | grep dwc_otg
[    0.445500] dwc_otg: version 3.00a 10-AUG-2012 (platform bus)
[    0.477050] dwc_otg 20980000.usb: base=(ptrval)
[    0.908713] WARN::dwc_otg_hcd_init:1074: FIQ DMA bounce buffers: virt = d9114000 dma = 0x59114000 len=9024
[    0.932523] dwc_otg: Microframe scheduler enabled
[    0.942367] dwc_otg 20980000.usb: DWC OTG Controller
[    0.945482] dwc_otg 20980000.usb: new USB bus registered, assigned bus number 1
[    0.948783] dwc_otg 20980000.usb: irq 56, io mem 0x00000000
[    0.971392] usb usb1: Manufacturer: Linux 4.19.113 dwc_otg_hcd
[    0.987040] dwc_otg: FIQ enabled
[    0.987052] dwc_otg: NAK holdoff enabled
[    0.987059] dwc_otg: FIQ split-transaction FSM enabled
```
## dmesg log when dwc2 was used
```bash
# dmesg | grep dwc
[    0.000000] Kernel command line: coherent_pool=1M bcm2708_fb.fbwidth=720 bcm2708_fb.fbheight=480 bcm2708_fb.fbswap=1 smsc95xx.macaddr=B8:27:EB:CF:61:8C vce
[    0.444855] dwc_otg: version 3.00a 10-AUG-2012 (platform bus)
[    0.448522] dwc_otg: FIQ enabled
[    0.448533] dwc_otg: NAK holdoff enabled
[    0.448540] dwc_otg: FIQ split-transaction FSM enabled
[    0.448559] Module dwc_common_port init
[    4.826413] dwc2 20980000.usb: 20980000.usb supply vusb_d not found, using dummy regulator
[    4.886471] dwc2 20980000.usb: Linked as a consumer to regulator.0
[    4.936271] dwc2 20980000.usb: 20980000.usb supply vusb_a not found, using dummy regulator
[    5.226404] dwc2 20980000.usb: dwc2_check_params: Invalid parameter lpm=1
[    5.236855] dwc2 20980000.usb: dwc2_check_params: Invalid parameter lpm_clock_gating=1
[    5.248228] dwc2 20980000.usb: dwc2_check_params: Invalid parameter besl=1
[    5.258534] dwc2 20980000.usb: dwc2_check_params: Invalid parameter hird_threshold_en=1
[    5.478154] dwc2 20980000.usb: EPs: 8, dedicated fifos, 4080 entries in SPRAM
[    5.537238] dwc2 20980000.usb: DWC OTG Controller
[    5.545541] dwc2 20980000.usb: new USB bus registered, assigned bus number 1
[    5.622567] dwc2 20980000.usb: irq 33, io mem 0x20980000
[    5.708694] usb usb1: Manufacturer: Linux 4.19.113 dwc2_hsotg
[   11.116324] dwc2 20980000.usb: bound driver configfs-gadget
[   11.478938] dwc2 20980000.usb: new device is high-speed
[   11.854789] dwc2 20980000.usb: new device is high-speed
[   11.935068] dwc2 20980000.usb: new device is high-speed
[   12.003670] dwc2 20980000.usb: new address 17
```

**Comment by tuyenld** [comment]
Test image for Pi Zero v1.3 (no Wi-Fi):
https://drive.google.com/file/d/11PZHnieRB96otPVOyj8wVykHk8OV5RFj/view?usp=sharing
I have no idea why the image is so big.

**Comment by htruong** [comment]
Thanks for the much-needed code and testing!

This looks pretty good to me, except for the `raspberry0_defconfig` that looks almost identical to `raspberry0cam_defconfig`. I wonder if we can programmatically create `raspberry0_defconfig` from `raspberry0cam_defconfig` and change only the bare minimum by `sed` in the `build.sh` script. 

That way we don't have to worry about the divergence between the two configs.

**Comment by tuyenld** [comment]
That is a good idea, I'll commit again.

**Pull request merged**
